### ISSUE TITLE
underline behavior

### ISSUE THREAD

**Issue by jraller** [aliftype/amiri#109]
The behavior of underlined text is different between Chrome and Firefox. Firefox renders the underline significantly lower than Chrome does under English text.

**Comment by khaledhosny** [comment]
The underline position in the font is tailored for Arabic since fonts currently do not have different underline positions for different scripts. Firefox uses the value from the font while Chrome does not. See also https://github.com/w3c/csswg-drafts/issues/459.

**Comment by attilatorcsvari** [comment]
I am aware, this is closed... yet similar behavior detected in Microsoft Word, whereas the line distance is also problematic.

Though this is not the primary purpose of this font, but, since even the Latin part is so beautiful,, couldn't there be a possibility to create a clone of this very same font with a distinguishable name, setting line height/underline distance for those would be delighted to use the Latin letters more than the Arabic letters? Thank you.

**Comment by khaledhosny** [comment]
Any one is free to make such clone of course, or one can directly use the original Latin font I re-used in Amiri: https://github.com/skosch/Crimson

**Comment by tuomassalo** [comment]
See this underline issue in action here: https://codepen.io/anon/pen/NeprWX

Here's a screenshot from Firefox 64 (left) and Chrome 71 (right) on macOS 10.13:

![amiri](https://user-images.githubusercontent.com/189964/50332030-8a9e8580-0509-11e9-8785-bce24c0ad0d8.png)
