### ISSUE TITLE
High (and low, for kasras) positioning of diacritics affects readability

### ISSUE THREAD

**Issue by mustafa0x** [aliftype/amiri#126]
Amiri is without doubt a beautiful font, and I'm using it on a high traffic site, but after comparing it to some other fonts I noticed that the position of the diacritics heavily affects readability, and requires a very high line-height.

Perhaps consider a version of the font where the diacritics are closer to their respective letters (even if that is not how the original Amiri font is)?

بوركتم

Related: #41

**Comment by khaledhosny** [comment]
I tried that early on and the result wasn’t that good. It wasn’t aesthetically pleasing and resulted in many vowel mark collisions. Most fonts get away with this by having smaller vowel marks and wider base characters, to things Amiri does not have (small marks are unreadable at text sizes, and the classical Naskh proportions results in generally narrower characters). Over the time I came to conclusion that the current positioning is the better option for Amiri’s design.

I don’t think Amiri requires an exceptionally large line height, and the default setting is reasonable and can be made even a bit more smaller without affecting readability. I generally believe that classical Naskh requires larger line spacing and it looks too cramped otherwise.

If you can show me the site you are using Amiri in, I can tell you what I think would be an optimal line height.

**Comment by khaledhosny** [comment]
I’m starting to change my mind again and might work on an option that enables variable vowel mark height, but it is quite a bit of work so I can’t commit to any time frame at the moment.

**Comment by khaledhosny** [comment]
Actually no, I think I’m going to live with that decision. May be one day when I re-do Amiri from scratch I’d consider such an option. Right now, too much work and too late anyway.
