### ISSUE TITLE
Alif hamza without tashkeel error in Amiri quran

### ISSUE THREAD

**Issue by philipzae** [aliftype/amiri#133]
![amiri quran error](https://user-images.githubusercontent.com/4412114/33215922-15fa62b4-d14b-11e7-9e35-44f9fa13d2b1.png)

**Comment by khaledhosny** [comment]
Amiri Quran contains only the subset of characters supported by Amiri font that are used in Quran, but this alef looks like U+0672 ARABIC LETTER ALEF WITH WAVY HAMZA ABOVE, which is not a character used in Quran (nor Arabic) AFAIK.  This looks like an authoring issue where the wrong character is used.

Here is the same sura using the text from https://github.com/khaledhosny/quran-data:
![screenshot-2017-11-24 amiri quran test](https://user-images.githubusercontent.com/93914/33222850-0e93d038-d163-11e7-8f7f-b370de1ce610.png)

**Comment by philipzae** [comment]
So i copied the text from here - http://read.quranexplorer.com/1/1/7/Usmani/Mishari-Rashid/Eng-Pickthal-Audio/Tajweed-OFF

![amiri quran error 1](https://user-images.githubusercontent.com/4412114/33225389-ea5462f0-d18f-11e7-9de3-71a526f46894.png)

**Comment by khaledhosny** [comment]
That looks like a misuse of Unicode characters by the font, to work around a limitation of some kind, a common thing in Quranic fonts due to historical or current limitations in common software. Amiri does not and cannot support such misuses.

The text in https://github.com/khaledhosny/quran-data is my best attempt to represent Quran using Unicode without resorting to such misuses, but I might revisit it the future to fellow some Unicode recommendations that I became aware of after I worked on this text, but this is a different issue.

**Comment by KrasnayaPloshchad** [comment]
@philipzae There has Bug Reporting link that you can feedback, so you can try to send a request for correction.
