### ISSUE TITLE
Italic text within bold with lualatex 

### ISSUE THREAD

**Issue by seloumi** [aliftype/amiri#139]
I have this issue 
https://github.com/latex3/latex2e/issues/7

The bolded text appear also italic

```latex
% lualatex 
\documentclass{article}
\usepackage{fontspec}
\setmainfont[Script=Arabic]{Amiri}

\begin{document}
\pardir TRT\textdir TRT

\textbf{إمكانيات}
\end{document}

```

**Comment by khaledhosny** [comment]
I can’t reproduce, I get bold text here: [test.pdf](https://github.com/alif-type/amiri/files/1632588/test.pdf)

**Comment by seloumi** [comment]
I have texlive 2017  

log file: 
[test2.log](https://github.com/alif-type/amiri/files/1632808/test2.log)
 
pdf file: 
[test2.pdf](https://github.com/alif-type/amiri/files/1632812/test2.pdf)

**Comment by khaledhosny** [comment]
The log is not telling me much. If it works with XeTeX but not LuaTeX then most likely it is a bug in luaotfload, but I can’t reproduce this to do any debugging.

One difference is that I have the fonts installed in system font directories, and your example is reading them from TEXMF tree, so that might be related. Can you try installing the fonts and see if it makes any difference.

**Comment by khaledhosny** [comment]
I removed the system fonts and even luaotfload cache and no difference.

**Comment by seloumi** [comment]
I have installed the fonts and the result is the same:  bold italic  rather then bold !

**Comment by seloumi** [comment]
I have installed the font and the result is the same:  bold italic  rather then bold !

**Comment by khaledhosny** [comment]
This really looks like a luaotfload bug, the fonts’ metadata are correct as far as I know, and no other application has issue with it.
