### ISSUE TITLE
Small Caps and additional glyphs from cochineal

### ISSUE THREAD

**Issue by SaadHafiane** [aliftype/amiri#140]
Could Small Caps  additional glyphs be added from Cochineal which is also an extension of the Crimson text font? or do the modifications introduced on Crimson to make it compatible with arabic Amiri glyphs make the task daunting?

**Comment by khaledhosny** [comment]
Crimson has small caps already, but I don’t include them in the Arabic font, why do you need them?

**Comment by AlHH** [comment]
Hi! We are using Amiri for our website “[In 2016—How it felt to live in the Arab World five years after the ‘Arab Spring’](http://folk.uio.no/albrech/In2016)“, and are generally very pleased with it. There is, however, one issue: on iOS, small caps for letters with diacritics used to transcribe certain Arabic letters (such as Ā, Ḍ, Ṣ, etc.) do not display and are replaced by <! > (exclamation mark followed by space). On both Windows and MacOS desktop computers, things work fine; same on Android. The problem only emerges on iOS. So here is one reason why one would need small caps in Amiri (since in classic typography, they are used to mark authors' names in bibliographic references). Pending a revised version of Amiri, is there any work-around solution? Unfortunately, the Crimson Text font provided by Google Fonts does not contain the needed diacritics; otherwise, I would have just changed the css to used Crimson Text in for the small caps spans.
If you want to have a look at our site, it is temporarily accessible using the credentials (user name: visitex) (pw: a1yAm#6102)

**Comment by khaledhosny** [comment]
Amiri does not contain any smallcaps at all, so what you see is regular capitals scaled down by the browser, so I don’t understand why those letters with diacritics would behave any differently. I don’t have any workarounds, unfortunately, since I don’t understand what is the problem to begin with. I can work and adding smallcaps, but I don’t have much free time so can’t make any promises on the timeline.
