### ISSUE TITLE
Diacritics Positioning

### ISSUE THREAD

**Issue by techana** [aliftype/amiri#149]
Upper diacritics (tashkil/harakat), such as Fatḥah, Dammah and Sukun, are placed way above letters. The large gaps between the diacritics and their letters result in the following two issues:

1. Readers may find difficulty in relating a diacritic to its letter. For example, it's not clear where the Fatḥah is in the word يتبَين
2. Diacritics overlap with above lines, especially with letters that go below the reference such as ع and إ

In addition, it's noticeable that the space (gap) between diacritics and letters is fixed. It would be better to dynamically position diacritics above letters. This would enhance the font's readability and would also solve the issue of overlapping diacritics of the same word, such as the Fatḥah and Sukun overlap in the word تَنْضم

**Comment by khaledhosny** [comment]
The relatively fixed vertical position of the marks is intentional, see previous issues about this. The overlap between lines is a result of too narrow line spacing, the default font line spacing shouldn’t cause this, if you are overriding it, try to increase it until no overlap happens. In general more generous line spacing is preferable for Arabic.
