### ISSUE TITLE
some words not showing properly in Urdu

### ISSUE THREAD

**Issue by mtabishs** [aliftype/amiri#82]
As Salam o Alaikum!
I liked your font very much.
But some words are not displaying properly.
![untitled](https://cloud.githubusercontent.com/assets/5260810/15284504/071c91e6-1b6b-11e6-9269-225845ecd638.png)

letter ک is almost taking the space of next letter, which makes it difficult to read.

Regards,
Muhammad Tabish Siddiqui
Islamabad, Pakistan

**Comment by khaledhosny** [comment]
This is by design. Amiri follows the traditional Naskh practice of joining the ك with the ا when there is a ب-like letter between them. You can prevent this, if you want, by inserting ZWJ (U+200D) after the ك,‎ `ك‍تاب`:
![a](https://cloud.githubusercontent.com/assets/93914/15777788/aff28a0e-299a-11e6-802b-7271a30a70c1.png)
